### ISSUE TITLE
Sprint 4

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico-web-api#14]
Objetivos:
- [x] Fazer a autenticação de usuário via Acesso Cidadão.
- [x] Implementar o CRUD Manter Tipo Documental
- [x] Entregar uma consulta de processos por número.
- [x] Servidor web do sistema

Métricas e Critérios:
A Sprint vai durar 1 semana e será considerada um sucesso caso:

- Um usuário autenticado no Acesso Cidadão consiga consultar processo por número no ambiente de desenvolvimento e manter Tipo Documental .
