### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by fontourafernando** [prodest/processo-eletronico-web-api#7]
Objetivos - Aumente suas chances de chegar aonde você quer, definindo onde você quer estar.

Um bom objetivo de Sprint deve ser específico e mensurável, ajudando o time a ter um propósito comum.

- Modelar parte do banco para atender as funcionalidades de autuar processo e consultar processos por número.
- Mapear as entidades do banco para a aplicação.

Entregáveis - O que será entregue nessa Sprint. Usando o markup do GitHub nós conseguimos listar e acompanhar facilmente cada situação.

- [x] #8 - Levantar os requisitos: Autuar processo
- [x] #6 - Modelar banco de dados
- [x] #2 - Implementar o entity framework
- [x] #1 - Implementar a injeção de dependência nas camadas

Métricas e Critérios - Quanto tempo a Sprint vai durar e quais são os critérios de aceitação? Incluindo essa informação fica fácil analisá-la futuramente.

A Sprint vai durar 1 semana e será considerada um sucesso caso:

- [x] Tabelas de parte do banco referente às funcionalidades de autuar processo e consultar processos por número criadas no banco de dados.
- [x] Objetos da aplicação mapeados para as tabelas do banco de dados.
- [x] Injeção de dependência sendo realizada entre as camadas.
